test

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -58,63 +58,63 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-          role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role_name }}
-          aws-region: ${{ inputs.aws_region }}
+      # - name: Configure AWS Credentials
+      #   uses: aws-actions/configure-aws-credentials@v3
+      #   with:
+      #     role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.role_name }}
+      #     aws-region: ${{ inputs.aws_region }}
 
-      - uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: ${{ inputs.terraform_version }}
+      # - uses: hashicorp/setup-terraform@v2
+      #   with:
+      #     terraform_version: ${{ inputs.terraform_version }}
 
-      - name: Terraform Init
-        id: init
-        run: >
-          terraform
-          -chdir="${{ inputs.terraform_dir }}"
-          init
-          -backend-config="key=${{ inputs.state_key }}"
-          -backend-config="bucket=${{ inputs.state_bucket }}"
-          -reconfigure
+      # - name: Terraform Init
+      #   id: init
+      #   run: >
+      #     terraform
+      #     -chdir="${{ inputs.terraform_dir }}"
+      #     init
+      #     -backend-config="key=${{ inputs.state_key }}"
+      #     -backend-config="bucket=${{ inputs.state_bucket }}"
+      #     -reconfigure
 
-      - name: Terraform Format
-        id: fmt
-        run: >
-          terraform
-          -chdir="${{ inputs.terraform_dir }}"
-          fmt
-          -check
-          -recursive
+      # - name: Terraform Format
+      #   id: fmt
+      #   run: >
+      #     terraform
+      #     -chdir="${{ inputs.terraform_dir }}"
+      #     fmt
+      #     -check
+      #     -recursive
 
-      - name: Terraform Validate
-        id: validate
-        run: >
-          terraform
-          -chdir="${{ inputs.terraform_dir }}"
-          validate
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: >
+      #     terraform
+      #     -chdir="${{ inputs.terraform_dir }}"
+      #     validate
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: >
-          terraform
-          -chdir="${{ inputs.terraform_dir }}"
-          plan
-          -no-color
-          -input=false
-          -lock=false
-          -var="environment=${{ inputs.environment }}"
-          -var="github_repo=${{ github.event.repository.name }}"
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request'
+      #   run: >
+      #     terraform
+      #     -chdir="${{ inputs.terraform_dir }}"
+      #     plan
+      #     -no-color
+      #     -input=false
+      #     -lock=false
+      #     -var="environment=${{ inputs.environment }}"
+      #     -var="github_repo=${{ github.event.repository.name }}"
+      #   continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: >
-          terraform
-          -chdir="${{ inputs.terraform_dir }}"
-          apply
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      #   run: >
+      #     terraform
+      #     -chdir="${{ inputs.terraform_dir }}"
+      #     apply
